name: woosignal
description: WooCommerce REST API for dart, connect a WooCommerce store and start developing with our interface for their API endpoints.
version: 1.1.1
homepage: https://woosignal.com
repository: https://github.com/woosignal/flutter-woocommerce-api
issue_tracker: https://github.com/woosignal/flutter-woocommerce-api/issues
documentation: https://woosignal.com/docs/api/1.0/overview

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  device_info: ^0.4.2+1
  shared_preferences: ^0.5.6+3
  uuid: ^2.0.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


